### ISSUE TITLE
bs4 should be renamed to beautifulsoup4 in setup.py

### ISSUE THREAD

**Issue by FunctionalHacker** [dbeley/ypc#19]
There is no python package called bs4, I'm guessing this was renamed at some point. This is causing ypc to fail for me, cause it can't find a module named bs4.

**Comment by dbeley** [comment]
Thanks, bs4 [do exists](https://pypi.org/project/bs4/), but it's actually a dummy package to beautifulsoup4 (It's kind of confusing because the package is named bs4 when you import it, but the real name is beautifulsoup4).

I've updated the setup.py with the correct name, hopefully it will resolve your problem.
Let me know if you have any other issues.

**Comment by FunctionalHacker** [comment]
Okay I still get the same error. I'm not much of a python dev myself so I might have been wrong about that. Here is the error:
```
❯ ypc
Traceback (most recent call last):
  File "/usr/bin/ypc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bs4' distribution was not found and is required by ypc
```

I'm on Arch Linux and installed ypc-git from the AUR

**Comment by dbeley** [comment]
Oops the AUR package also had some dependencies errors, I think I've fixed them. You might need to cleanbuild the package (if you use the yay AUR helper there is a prompt, otherwise just delete the ypc repo somewhere in your ~/.cache directory).

Thanks for testing !

**Comment by FunctionalHacker** [comment]
Thanks a lot, it works now!
